### ISSUE TITLE
Making a local debug build

### ISSUE THREAD

**Issue by RonaldDijks** [maxwellpollack/juce-plugin-ci#1]
Thanks for the nice example of how to work with the JUCE CMake API, it really helps to get started quickly with building a project on GitHub CI. 

It would be really nice if the README.md contained the steps to make local debug build on different platforms (WIN/OSX/LINUX). I would send in a pull request, but I haven't figured it out quite yet :p

**Comment by ellamenop** [comment]
Hey, thanks for making an issue! I've been meaning to add some more thorough "Getting Started"-type instructions, but have been short on time. I just added a few quick guides to building from the command line (UNIX) and in Visual Studio Code. Would love to hear how you make out!
